---
- name: set password
  hosts: 10.0.1.11
  become: true

  tasks:
  - name: set password for ansible user
    user:
     name: ansible
     update_password: always
     password: "{{'12345' | password_hash ('sha512')}}"
