---
- name: download from internet
  hosts: 10.0.1.11
  become: true

  tasks:
  - name: download from internet
    get_url:
     url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
     dest: /home/ubuntu/
     owner: ubuntu
     group: ubuntu
     mode: 0774
