---
- name: usage of conditions
  hosts: 10.0.1.11
  become: true

  tasks:
  - name: uninstall nginx on redhat
    yum:
     name: nginx
     state: absent
    when: ansible_os_family== "redhat"

  - name: uninstall nginx on ubuntu
    apt:
     name: nginx
     state: absent
    when: ansible_os_family== "ubuntu"
